-- Insert default bar products

CALL bar_rest.CreateProduct('Pilsen', 'Botella de cerveza nacional marca Pilsen.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Pilsen 6.0', 'Botella de cerveza nacional marca Pilsen 6.0.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Imperial', 'Botella de cerveza nacional marca Imperial.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Imperial Silver', 'Botella de cerveza nacional marca Imperial Silver.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Imperial Ultra', 'Botella de cerveza nacional marca Imperial Ultra.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Imperial Light', 'Botella de cerveza nacional marca Imperial Light.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Imperial Cero', 'Botella de cerveza nacional sin alcohol marca Imperial Cero.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Rock con Limón', 'Botella de cerveza nacional marca Rock con Limón.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Corona', 'Botella de cerveza extranjera marca Corona.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Sol', 'Botella de cerveza extranjera marca Sol.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Heineken', 'Botella de cerveza extranjera marca Heineken.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Heineken 0', 'Botella de cerveza extranjera sin alcohol marca Heineken 0.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Bambú Daikiry', 'Botella de coctel daikiri marca Bambú.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Bambú Mojito', 'Botella de coctel mojito marca Bambú.', 100, 2000, 1, 1, 1);
CALL bar_rest.CreateProduct('Coca Cola', 'Botella de refresco marca Coca Cola.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Fanta Kolita', 'Botella de refresco de kola marca Fanta.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Fanta Naranja', 'Botella de refresco de naranja marca Fanta.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Fresca', 'Botella de refresco de toronja marca Fresca.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Ginger ale', 'Botella de refresco de gin marca Ginger ale.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Soda', 'Botella de soda marca Ginger ale.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Tropical Té Melocotón', 'Botella de Té de Melocotón marca Tropical.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Tropical Té Blanco', 'Botella de Té de Blanco marca Tropical.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Tropical Frutas', 'Botella de refresco de frutas marca Tropical.', 100, 1300, 1, 1, 1);
CALL bar_rest.CreateProduct('Carta Blanca', 'Lata de cerveza extranjera marca Carta Blanca.', 100, 1000, 1, 2, 1);
CALL bar_rest.CreateProduct('Pilsen', 'Lata de cerveza nacional marca Pilsen.', 100, 1300, 1, 2, 1);
CALL bar_rest.CreateProduct('Imperial', 'Lata de cerveza nacional marca Imperial.', 100, 1300, 1, 2, 1);
CALL bar_rest.CreateProduct('Imperial Silver', 'Lata de cerveza nacional marca Imperial Silver.', 100, 1300, 1, 2, 1);
CALL bar_rest.CreateProduct('Cuba Libre', 'Lata de coctél de Cola con Ron marca Cuba Libre.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Coca Cola Jack Daniels', 'Lata de coctél de Cola con Whisky marca Jack Daniels.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Smirnoff Manzana', 'Lata de coctél de manzana con Vodka marca Smirnoff.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Smirnoff Guaraná', 'Lata de coctél de guaraná con Vodka marca Smirnoff.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Smirnoff Mango', 'Lata de coctél de mango con Vodka marca Smirnoff.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Smirnoff Limón', 'Lata de coctél de limón con Vodka marca Smirnoff.', 100, 2000, 1, 2, 1);
CALL bar_rest.CreateProduct('Jugazo Manzana', 'Lata de refresco de manzana marca Jugazo.', 100, 1500, 1, 2, 1);
CALL bar_rest.CreateProduct('Jugazo Pera', 'Lata de refresco de pera marca Jugazo.', 100, 1500, 1, 2, 1);
CALL bar_rest.CreateProduct('Jugazo Melocotón', 'Lata de refresco de melocotón marca Jugazo.', 100, 1500, 1, 2, 1);
CALL bar_rest.CreateProduct('Jugazo Piña', 'Lata de refresco de piña marca Jugazo.', 100, 1500, 1, 2, 1);
CALL bar_rest.CreateProduct('Jugazo Frutas', 'Lata de refresco de frutas marca Jugazo.', 100, 1500, 1, 2, 1);
CALL bar_rest.CreateProduct('Chifrijo', 'Boca de Chifrijo con chicharones, snack tostados junto con arroz y frjoles rojos', 1, 3500, 1, 3, 1);
CALL bar_rest.CreateProduct('Chicharrones', 'Boca de chicharones', 1, 4000, 1, 3, 1);
CALL bar_rest.CreateProduct('Alitas de pollo', 'Boca de alitas de pollo', 1, 3500, 1, 3, 1);
CALL bar_rest.CreateProduct('Fajitas', 'Boca de fajitas', 1, 3500, 1, 3, 1);
CALL bar_rest.CreateProduct('Costilla', 'Boca de costilla de cerdo', 1, 4500, 1, 3, 1);
CALL bar_rest.CreateProduct('Trocitos de pollo', 'Boca de trocitos de pollo', 1, 3500, 1, 3, 1);
CALL bar_rest.CreateProduct('Filete de pescado', 'Boca de filete de pescado', 1, 4000, 1, 3, 1);
CALL bar_rest.CreateProduct('Salchipapas', 'Boca de papas fritas con salchichas.', 1, 3500, 1, 3, 1);
CALL bar_rest.CreateProduct('Surtido 2 personas', 'Surtido con chicharrones, pollo y pescado para 2 personas.', 1, 8500, 1, 3, 1);
CALL bar_rest.CreateProduct('Surtido 5 personas', 'Surtido con chicharrones, pollo y pescado para 5 personas.', 1, 15500, 1, 3, 1);
CALL bar_rest.CreateProduct('Surtido 7 personas', 'Surtido con chicharrones, pollo y pescado para 7 personas.', 1, 18500, 1, 3, 1);
CALL bar_rest.CreateProduct('Papas fritas', 'Snack de papas fritas.', 1, 2500, 1, 4, 1);
CALL bar_rest.CreateProduct('Yucas fritas', 'Snack de yucas fritas.', 1, 2500, 1, 4, 1);
CALL bar_rest.CreateProduct('Patacones', 'Snack de patacones.', 1, 4000, 1, 4, 1);
CALL bar_rest.CreateProduct('Maní Salado', 'Snack de maní salado.', 50, 500, 1, 5, 1);
CALL bar_rest.CreateProduct('Maní con Limón', 'Snack de maní con limón.', 50, 500, 1, 5, 1);
CALL bar_rest.CreateProduct('Maní Garapiñado', 'Snack de maní garapiñado.', 50, 500, 1, 5, 1);
CALL bar_rest.CreateProduct('Shot Chiliguarito Tomate', 'Shot de chiliguaro sabor Tomate marca Chiliguarito', 1, 700, 1, 6, 1);
CALL bar_rest.CreateProduct('Grande Chiliguarito Tomate', 'Trago grande de chiliguaro sabor Tomate marca Chiliguarito', 1, 1000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chiliguarito Tomate', 'Cuarta de chiliguaro sabor Tomate marca Chiliguarito', 1, 2000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chiliguarito Tomate', 'Media de chiliguaro sabor Tomate marca Chiliguarito', 1, 3000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Chiliguarito Maracuyá', 'Shot de chiliguaro sabor maracuyá marca Chiliguarito', 1, 700, 1, 6, 1);
CALL bar_rest.CreateProduct('Grande Chiliguarito Maracuyá', 'Trago grande de chiliguaro sabor maracuyá marca Chiliguarito', 1, 1000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chiliguarito Maracuyá', 'Cuarta de chiliguaro sabor maracuyá marca Chiliguarito', 1, 2000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chiliguarito Maracuyá', 'Media de chiliguaro sabor maracuyá marca Chiliguarito', 1, 3000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Chiliguarito Mango', 'Shot de chiliguaro sabor mango marca Chiliguarito', 1, 700, 1, 6, 1);
CALL bar_rest.CreateProduct('Grande Chiliguarito Mango', 'Trago grande de chiliguaro sabor mango marca Chiliguarito', 1, 1000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chiliguarito Mango', 'Cuarta de chiliguaro sabor mango marca Chiliguarito', 1, 2000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chiliguarito Mango', 'Media de chiliguaro sabor mango marca Chiliguarito', 1, 3000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Chiliguarito Cas', 'Shot de chiliguaro sabor cas marca Chiliguarito', 1, 700, 1, 6, 1);
CALL bar_rest.CreateProduct('Grande Chiliguarito Cas', 'Trago grande de chiliguaro sabor cas marca Chiliguarito', 1, 1000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chiliguarito Cas', 'Cuarta de chiliguaro sabor cas marca Chiliguarito', 1, 2000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chiliguarito Cas', 'Media de chiliguaro sabor cas marca Chiliguarito', 1, 3000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Chiliguarito Tamarindo', 'Shot de chiliguaro sabor tamarindo marca Chiliguarito', 1, 700, 1, 6, 1);
CALL bar_rest.CreateProduct('Grande Chiliguarito Tamarindo', 'Trago grande de chiliguaro sabor tamarindo marca Chiliguarito', 1, 1000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chiliguarito Tamarindo', 'Cuarta de chiliguaro sabor tamarindo marca Chiliguarito', 1, 2000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chiliguarito Tamarindo', 'Media de chiliguaro sabor tamarindo marca Chiliguarito', 1, 3000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Jhonhy Walker Negra', 'Shot de Whiskey marca Jhonhy Walker Etiqueta Negra', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Jhonhy Walker Negra', 'Trago pequeño de Whiskey marca Jhonhy Walker Etiqueta Negra', 1, 3000, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Jhonhy Walker Negra', 'Trago grande de Whiskey marca Jhonhy Walker Etiqueta Negra', 1, 4000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Jhonhy Walker Negra', 'Cuarta de Whiskey marca Jhonhy Walker Etiqueta Negra', 1, 11500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Jhonhy Walker Negra', 'Media de Whiskey marca Jhonhy Walker Etiqueta Negra', 1, 22000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Old Parr', 'Shot de Whiskey marca Old Parr', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Old Parr', 'Trago pequeño de Whiskey marca Old Parr', 1, 3000, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Old Parr', 'Trago grande de Whiskey marca Old Parr', 1, 4000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Old Parr', 'Cuarta de Whiskey marca Old Parr', 1, 11500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Old Parr', 'Media de Whiskey marca Old Parr', 1, 22000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Chivas', 'Shot de Whiskey marca Chivas', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Chivas', 'Trago pequeño de Whiskey marca Chivas', 1, 3000, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Chivas', 'Trago grande de Whiskey marca Chivas', 1, 4000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Chivas', 'Cuarta de Whiskey marca Chivas', 1, 11500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Chivas', 'Media de Whiskey marca Chivas', 1, 22000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Jack Daniels', 'Shot de Whiskey marca Jack Daniels', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Jack Daniels', 'Trago pequeño de Whiskey marca Jack Daniels', 1, 3000, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Jack Daniels', 'Trago grande de Whiskey marca Jack Daniels', 1, 4000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Jack Daniels', 'Cuarta de Whiskey marca Jack Daniels', 1, 11500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Jack Daniels', 'Media de Whiskey marca Jack Daniels', 1, 22000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Jhonhy Walker Rojo', 'Shot de Whiskey marca Jhonhy Walker Etiqueta Roja.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Jhonhy Walker Rojo', 'Trago pequeño de Whiskey marca Jhonhy Walker Etiqueta Roja.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Jhonhy Walker Rojo', 'Trago grande de Whiskey marca Jhonhy Walker Etiqueta Roja.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Jhonhy Walker Rojo', 'Cuarta de Whiskey marca Jhonhy Walker Etiqueta Roja,', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Jhonhy Walker Rojo', 'Media de Whiskey marca Jhonhy Walker Etiqueta Roja,', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot JyB', 'Shot de Whiskey marca JyB.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño JyB', 'Trago pequeño de Whiskey marca JyB.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande JyB', 'Trago grande de Whiskey marca JyB.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ JyB', 'Cuarta de Whiskey marca JyB,', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ JyB', 'Media de Whiskey marca JyB,', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Passport', 'Shot de Whiskey marca Passport.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Passport', 'Trago pequeño de Whiskey marca Passport.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Passport', 'Trago grande de Whiskey marca Passport.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Passport', 'Cuarta de Whiskey marca Passport,', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Passport', 'Media de Whiskey marca Passport,', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Black & White', 'Shot de Whiskey marca Black & White.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Black & White', 'Trago pequeño de Whiskey marca Black & White.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Black & White', 'Trago grande de Whiskey marca Black & White.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Black & White', 'Cuarta de Whiskey marca Black & White,', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Black & White', 'Media de Whiskey marca Black & White,', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Baileys', 'Shot de crema con Whiskey marca Baileys.', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Baileys', 'Trago pequeño de crema con Whiskey marca Baileys.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Baileys', 'Trago grande de crema con Whiskey marca Baileys.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Baileys', 'Cuarta de crema con Whiskey marca Baileys,', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Baileys', 'Media de crema con Whiskey marca Baileys,', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Tequla oscuro', 'Shot de Tequla oscuro.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Tequla oscuro', 'Trago pequeño de Tequla oscuro.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Tequla oscuro', 'Trago grande de Tequla oscuro.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Tequla oscuro', 'Cuarta de Tequla oscuro.', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Tequla oscuro', 'Media de Tequla oscuro.', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Tequla claro', 'Shot de Tequla claro.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Tequla claro', 'Trago pequeño de Tequla claro.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Tequla claro', 'Trago grande de Tequla claro.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Tequla claro', 'Cuarta de Tequla claro.', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Tequla claro', 'Media de Tequla claro.', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Tequla Rose', 'Shot de Tequla Rose.', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Tequla Rose', 'Trago pequeño de Tequla Rose.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Tequla Rose', 'Trago grande de Tequla Rose.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Tequla Rose', 'Cuarta de Tequla Rose.', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Tequla Rose', 'Media de Tequla Rose.', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Malibú', 'Shot de ron de coco marca Malibú.', 1, 2000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Malibú', 'Trago pequeño de ron de coco marca Malibú.', 1, 2500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Malibú', 'Trago grande de ron de coco marca Malibú.', 1, 3000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Malibú', 'Cuarta de ron de coco marca Malibú.', 1, 8000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Malibú', 'Media de ron de coco marca Malibú.', 1, 15000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Ron Rico', 'Shot de ron marca Ron Rico.', 1, 1200, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Ron Rico', 'Trago pequeño de ron marca Ron Rico.', 1, 1700, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Ron Rico', 'Trago grande de ron marca Ron Rico.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Ron Rico', 'Cuarta de ron marca Ron Rico.', 1, 6000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Ron Rico', 'Media de ron marca Ron Rico.', 1, 12000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Bacardi', 'Shot de ron marca Bacardi.', 1, 1200, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Bacardi', 'Trago pequeño de ron marca Bacardi.', 1, 1700, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Bacardi', 'Trago grande de ron marca Bacardi.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Bacardi', 'Cuarta de ron marca Bacardi.', 1, 6000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Bacardi', 'Media de ron marca Bacardi.', 1, 12000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Flor de caña', 'Shot de ron marca Flor de caña.', 1, 1200, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Flor de caña', 'Trago pequeño de ron marca Flor de caña.', 1, 1700, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Flor de caña', 'Trago grande de ron marca Flor de caña.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Flor de caña', 'Cuarta de ron marca Flor de caña.', 1, 6000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Flor de caña', 'Media de ron marca Flor de caña.', 1, 12000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Cortez', 'Shot de ron marca Cortez.', 1, 1200, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Cortez', 'Trago pequeño de ron marca Cortez.', 1, 1700, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Cortez', 'Trago grande de ron marca Cortez.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Cortez', 'Cuarta de ron marca Cortez.', 1, 6000, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Cortez', 'Media de ron marca Cortez.', 1, 12000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Centenario', 'Shot de ron marca Centenario.', 1, 1500, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Centenario', 'Trago pequeño de ron marca Centenario.', 1, 2000, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Centenario', 'Trago grande de ron marca Centenario.', 1, 2500, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Centenario', 'Cuarta de ron marca Centenario.', 1, 6500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Centenario', 'Media de ron marca Centenario.', 1, 13000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Cacique', 'Shot de guaro marca Cacique.', 1, 1000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Cacique', 'Trago pequeño de guaro marca Cacique.', 1, 1500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Cacique', 'Trago grande de guaro marca Cacique.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Cacique', 'Cuarta de guaro marca Cacique.', 1, 4500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Cacique', 'Media de guaro marca Cacique.', 1, 8000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Anis', 'Shot de Anis.', 1, 1000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Anis', 'Trago pequeño de Anis.', 1, 1500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Anis', 'Trago grande de Anis.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Anis', 'Cuarta de Anis.', 1, 4500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Anis', 'Media de Anis.', 1, 8000, 1, 10, 1);
CALL bar_rest.CreateProduct('Shot Agua Ardiente', 'Shot de Agua Ardiente.', 1, 1000, 1, 6, 1);
CALL bar_rest.CreateProduct('Pequeño Agua Ardiente', 'Trago pequeño de Agua Ardiente.', 1, 1500, 1, 7, 1);
CALL bar_rest.CreateProduct('Grande Agua Ardiente', 'Trago grande de Agua Ardiente.', 1, 2000, 1, 8, 1);
CALL bar_rest.CreateProduct('¼ Agua Ardiente', 'Cuarta de Agua Ardiente.', 1, 4500, 1, 9, 1);
CALL bar_rest.CreateProduct('½ Agua Ardiente', 'Media de Agua Ardiente.', 1, 8000, 1, 10, 1);
CALL bar_rest.CreateProduct('Taza Café', 'Taza de café de la casa caliente.', 1, 2000, 1, 11, 1);
CALL bar_rest.CreateProduct('Taza Café con Leche', 'Taza de café de la casa con leche caliente.', 1, 2000, 1, 11, 1);
CALL bar_rest.CreateProduct('Taza Té', 'Taza de Té de la casa caliente.', 1, 2000, 1, 11, 1);
CALL bar_rest.CreateProduct('Taza Agua Dulce (DulceT)', 'Taza de Agua Dulce (DulceT) caliente.', 1, 2000, 1, 11, 1);
CALL bar_rest.CreateProduct('Taza Capuccino', 'Taza de capuccino de la casa caliente.', 1, 2000, 1, 11, 1);